#!/bin/bash

# functions
#
function clear_cache() {
su -c "echo 3 >'/proc/sys/vm/drop_caches' && swapoff -a" root
}
function echo_cores() {
echo Cores = $(( $(lscpu | awk '/^Socket/{ print $2 }') * $(lscpu | awk '/^Core/{ print $4 }') ))
}
connected_ips() {
netstat -ntu | awk '{print $5}' | cut -d: -f1 | grep -v -E "servers\)|Address" | sort | uniq -c | sort -n
}

# get server IP address
# commented because unused
#server_ip=$(hostname -I | awk '{print $1}')


printf " Hello man. \n What is up? "
sleep 1
printf "Here is the list, pick something: 

	1. show cpu core numbers.\n
	2. show memory/RAM info.\n
	3. clear swap and RAM cache.\n
	4. ----------------------.\n
	5. ----------------------.\n
	6. check connected IPs.\n
	7. change nameservers.\n 
	8. find a user's files\n\n"

# get task numer from user
#
read -rp "pick a task: " choice

printf " \n -------------------------------------------------\n"

# case statement
#
case $choice in
  1) echo_cores
	;;
  2) echo "--------MEMORY INFO--------" 
     grep 'Mem\|Swap' /proc/meminfo
	;;
  3) clear_cache 
     echo "cache cleared succesfully."
     read -rp "would you like to turn on swap memory?(y/n)" swap_state
     case $swap_state in
       "y") swapon -a ;;
       "n") swapoff -a ;;
       *) echo "Wrong input!"
     esac
	;;
  4) echo "not yet"
	;;
  5) echo "not yet"
	;;
  6) echo "------CONNECTED IPs------"
     connected_ips
	;;
  7) read -rp "select nameservers (google/shecan/electro/403) _> " nameservers
    case $nameservers in
      "google") echo -e "nameserver 8.8.8.8 \nnameserver 8.8.4.4 \n" > /etc/resolv.conf
      ;;
      "shecan") echo -e "nameserver 178.22.122.100 \nnameserver 78.157.42.100 \n" > /etc/resolv.conf
      ;;
      "electro") echo -e "nameserver 78.157.42.101 \nnameserver 78.157.42.100 \n" > /etc/resolv.conf
      ;;
      "403") echo -e "nameserver 10.202.10.202 \nnameserver 10.202.10.102 \n" > /etc/resolv.conf
      ;;
      *) echo "Wrong nameservers selected"
    esac 
	;;
  8) read -rp "give me the username  : " user_name
     uid=$(id -u "$user_name")
     find / -type f -uid "$uid" -print0 | xargs -0 du -h | sort -h -r > userfiles.txt
     echo "$user_name files have been saved into 'userfiles.txt'"
	;;
esac
